kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 32000
        hostPort: 80
      # Airflow
      - containerPort: 8080
        hostPort: 8080
      # Argo CD
      # Argo Workflows
      # Argo Events
