---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: lutherlabs-data-apps-project
  sources:
    - repoURL: 'https://github.com/luthes/dpib'
      targetRevision: master
      ref: values
    - chart: airflow
      repoURL: https://airflow.apache.org
      targetRevision: 1.8.0
      helm:
        valueFiles:
          - $values/apps-data/airflow/values.yaml
      releaseName: airflow
  destination:
    server: "https://kubernetes.default.svc"
    namespace: data-apps
  syncPolicy:
    automated:
      prune: true

