apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: data-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    #- matrix:
    #    generators:
    #      - git:
    #          repoURL: https://github.com/luthes/dpib
    #          revision: master
    #          directories:
    #            - path: apps-data/*
    - list:
        elements:
          - cluster: dev-airflow
            url: https://kubernetes.default.svc
            project: lutherlabs-data-apps-project-dev
            namespace: data-apps-dev
            helmRepoURL: https://airflow.apache.org/
            helmChart: airflow
            helmValuesRepo: https://github.com/luthes/dpib
            helmValuesBranch: master
            helmValueFiles:
              - values.yaml # should be a full path to the repo prob
          # - cluster: prod-airflow
          #   url: https://kubernetes.default.svc
          #   project: lutherlabs-data-apps-project-prod
          #   namespace: data-apps-prod
          #   helmRepoURL: https://airflow.apache.org/
          #   helmChart: airflow
          #   helmValuesRepo: https://github.com/luthes/dpib
          #   helmValuesBranch: master
          #   helmValueFiles:
          #     - values.yaml # should be a full path to the repo prob
  template:
    metadata:
      name: '{{ .cluster }}-{{ .helmChart }}'
    spec:
      project: '{{ .project }}'
      sources:
        - repoURL: '{{ .helmValuesRepo }}'
          targetRevision: '{{ .helmValuesBranch }}'
          ref: RepoValues
        - chart: '{{ .helmChart }}'
          repoURL: '{{ .helmRepoURL }}'
          targetRevision: 1.8.0
          helm:
            valueFiles:
              # This should change to be env specific
              # - values.yaml
              - https://github.com/luthes/dpib/apps-data/values.yaml
            releaseName: '{{ .cluster }}'
      destination:
        server: '{{ .url }}'
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          prune: true
