apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: data-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    #- matrix:
    #    generators:
    #      - git:
    #          repoURL: https://github.com/luthes/dpib
    #          revision: master
    #          directories:
    #            - path: apps-data/*
    - list:
        elements:
          - cluster: dev-superset
            url: https://kubernetes.default.svc
            project: lutherlabs-data-apps-project-dev
            namespace: data-apps-dev
            helmRepoURL: https://apache.github.io/superset
            helmChart: superset
            helmValuesRepo: https://github.com/luthes/dpib
            helmValuesPath: apps-data/superset/values.yaml
            helmValuesBranch: master
            helmTargetRevision: 0.8.10
            helmValueFiles:
              - values.yaml # should be a full path to the repo prob
          - cluster: dev-airflow
            url: https://kubernetes.default.svc
            project: lutherlabs-data-apps-project-dev
            namespace: data-apps-dev
            helmRepoURL: https://airflow.apache.org/
            helmChart: airflow
            helmValuesRepo: https://github.com/luthes/dpib
            helmValuesPath: apps-data/airflow/values.yaml
            helmValuesBranch: master
            helmTargetRevision: 1.8.0
            helmValueFiles:
              - values.yaml # should be a full path to the repo prob
          - cluster: dev-airbyte
            url: https://kubernetes.default.svc
            project: lutherlabs-data-apps-project-dev
            namespace: data-apps-dev
            helmRepoURL: https://airbytehq.github.io/helm-charts
            helmChart: airbyte
            helmValuesRepo: https://github.com/luthes/dpib
            helmValuesPath: apps-data/airbyte/values.yaml
            helmValuesBranch: master
            helmTargetRevision: 0.45.5
            helmValueFiles:
              - values.yaml # should be a full path to the repo prob
          # - cluster: prod-airflow
          #   url: https://kubernetes.default.svc
          #   project: lutherlabs-data-apps-project-prod
          #   namespace: data-apps-prod
          #   helmRepoURL: https://airflow.apache.org/
          #   helmChart: airflow
          #   helmValuesRepo: https://github.com/luthes/dpib
          #   helmValuesBranch: master
          #   helmValueFiles:
          #     - values.yaml # should be a full path to the repo prob
  template:
    metadata:
      name: '{{ .cluster }}-{{ .helmChart }}'
    spec:
      project: '{{ .project }}'
      sources:
        - repoURL: '{{ .helmValuesRepo }}'
          targetRevision: '{{ .helmValuesBranch }}'
          ref: RepoValues
        - chart: '{{ .helmChart }}'
          repoURL: '{{ .helmRepoURL }}'
          targetRevision: '{{ .helmTargetRevision }}'
          helm:
            valueFiles:
              - '$RepoValues/{{ .helmValuesPath }}'
            releaseName: '{{ .cluster }}'
      destination:
        server: '{{ .url }}'
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          prune: true
