apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: data-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/luthes/dpib
              revision: master
              directories:
                - path: apps-data/*
          - list:
              elements:
                - cluster: dev
                  url: https://kubernetes.default.svc
                  values:
                    project: lutherlabs-data-apps-project-dev
                - cluster: prod
                  url: https://kubernetes.default.svc
                  values:
                    project: lutherlabs-data-apps-project-prod
  template:
    metadata:
      name: '{{ .path.basename }}-{{ .cluster }}'
    spec:
      project: '{{ .values.project }}'
      source:
        repoURL: https://github.com/luthes/dpib.git
        targetRevision: master
        path: '{{ .path.path }}'
      destination:
        server: '{{ .url }}'
        namespace: '{{ .path.basename }}'
