spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/luthes/dpib'
    targetRevision: master
syncPolicy:
  automated:
    prune: true
values:
  airflow:
    app_name: airflow
