---
kind: Namespace
apiVersion: v1
metadata:
  name: argocd
  labels:
    name: argocd
    istio-injection: enabled
---
kind: Namespace
apiVersion: v1
metadata:
  name: apps
  labels:
    name: apps
    istio-injection: enabled
