apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-application
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  project: dev-data-apps
  source:
    repoURL: https://airflow.apache.org
    targetRevision: 1.7.0
    chart: apache-airflow
    helm:
      valueFiles:
        - values/airflow/dev.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
