---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apache-airflow
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: {{.Values.spec.destination.server}}
  project: default
  source:
    repoURL: https://airflow.apache.org
    targetRevision: 1.7.0
    chart: airflow
    helm:
      valueFiles:
        - values/airflow/dev.yaml
