apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
                "access":"proxy",
                "editable": true,
                "name": "prometheus",
                "orgId": 1,
                "type": "prometheus",
                # my-service.my-namespace.svc
                "url": "http://prometheus-loadbalancer.monitoring.svc:8001",
                "version": 1
            }
        ]
    }
