---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airbyte
  namespace: argocd
  labels:
    name: dev-data-apps
    environment: dev
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: infra-dev
  source:
    path: ./data-apps/airbyte
    repoURL: git@github.com:luthes/dpib
    targetRevision: development
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions: # Sync options which modifies sync behavior
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
