---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-controller
  namespace: argocd
spec:
  project: lutherlabs-system
  source:
    chart: nginx-ingress
    repoURL: https://helm.nginx.com/stable
    targetRevision: 0.16.2
    helm:
      releaseName: nginx-ingress
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nginx-system
  syncPolicy:
    automated:
      prune: true
